AWSTemplateFormatVersion: '2010-09-09'
Description: 'This CloudFormation script provisions a RDS instance(s). '
Parameters:
  SQLServerInstance:
    Description: SQL Server RDS Instance Name
    Type: String

  SQLServerInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.t3.xlarge

  SQLServerInstanceEngine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    AllowedValues: [sqlserver-ee, sqlserver-se, sqlserver-ex, sqlserver-web]
    ConstraintDescription: "Please specify either a sqlserver-ee, sqlserver-se, sqlserver-ex, or sqlserver-web engine for the RDS instance."

  SQLServerInstanceMasterUsername:
    Description: The master user name for the DB instance.
    Type: String

  SQLServerInstanceMasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    NoEcho: true

  DBInputCIDR:
    Description: CIDR  to allow access to DB instances
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  DBPortNumber:
    Description: The port number on which the database accepts connections.
    Type: Number
    Default: '1433'
    MinValue: '1433'
    MaxValue: '1433'
    ConstraintDescription: 1150-65535 except for 1434, 3389, 47001, 49152, and 49152

  Storage:
    Description: The allocated storage size, specified in gigabytes (GB).
    Type: String
    AllowedPattern: "^([2-9]?[0-9]{1}|[0-9]{3,4}|1[0-5]?[0-9]{3}|16[0-2]?[0-9]{2}|163[0-7]?[0-9]{1}|1638[0-4]?)$"
    ConstraintDescription: "Value must be a valid number between 20-16384."

  DBVPC:
    Description: VPC in which RDS instance will reside
    Type: AWS::EC2::VPC::Id

  PrivateSubnet01:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet for the DB cluster
    Default: subnet-ID

  PrivateSubnet02:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet for the DB cluster
    Default: subnet-ID

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: SQL Server Instance Details
      Parameters:
        - SQLServerInstance
        - SQLServerInstanceEngine
        - SQLServerInstanceClass
        - Storage
        - SQLServerInstanceMasterUsername
        - SQLServerInstanceMasterUserPassword
        - DBPortNumber
        - DBVPC
        - PrivateSubnet01
        - PrivateSubnet02
        - DBInputCIDR

Resources:
  RDSSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Database instances security group"
            VpcId: !Ref DBVPC

  SGBaseIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDSSecurityGroup
      IpProtocol: tcp
      FromPort: !Ref DBPortNumber
      ToPort: !Ref DBPortNumber
      CidrIp: !Ref DBInputCIDR

  RDSDBSubnetGroup:
        Type: "AWS::RDS::DBSubnetGroup"
        Properties:
            DBSubnetGroupDescription: "Subnet Group for mySQL database"
            DBSubnetGroupName: !Sub "${AWS::Region}-aws-dxl-database-subnet-group"
            SubnetIds:
              - !Ref PrivateSubnet01
              - !Ref PrivateSubnet02

  SQLServerRDSInstanceCreation:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref SQLServerInstance
      AllocatedStorage: !Ref Storage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod:  7
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref SQLServerInstanceClass
      Engine: !Ref SQLServerInstanceEngine
      EngineVersion: "15.00.4073.23.v1"
      LicenseModel: license-included
      MasterUsername: !Ref SQLServerInstanceMasterUsername
      MasterUserPassword: !Ref SQLServerInstanceMasterUserPassword
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      MultiAZ: false
      MonitoringInterval: 0
      PubliclyAccessible: false
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
          - ${AWS::StackName}-${Name}
          - { Name: !Ref SQLServerInstanceEngine }
